/*
 * Project :      1Equipo-Appsafe-informes y estadisticas
 * Authors :      Alvarez Lopez Carlos Manuel
				  Membrilla Isaias I�aki Ramos
				  Miramón Pérez Jocelyn
 *
 */

 USE [APPSAFE]
 GO

/*
 * 1. Viajes diarios por conductor; datos del conductor, numero de viajes, monto total, este informe debe poder
 * obtener por un periodo de tiempo
*/

CREATE PROCEDURE OBTENER_DATOS_CONDUCTOR
	@FECHA_INICIO DATE,
	@FECHA_FIN DATE
AS
BEGIN

    WITH VIAJES_POR_CONDUCTOR AS (
        SELECT 
            C.ID_USUARIO,
            COUNT(V.ID_VIAJE) AS NUMERO_DE_VIAJES,
            SUM(V.IMPORTE) AS MONTO
        FROM USUARIOS.CONDUCTOR AS C
        JOIN USUARIOS.AUTOMOVIL AS A ON A.ID_USUARIO = C.ID_USUARIO
        JOIN OPERACIONES.VIAJE AS V ON V.ID_AUTOMOVIL = A.ID_AUTOMOVIL
        WHERE V.FECHA_INICIOVIAJE BETWEEN @FECHA_INICIO AND @FECHA_FIN
        GROUP BY C.ID_USUARIO
    )


    SELECT 
        C.ID_USUARIO, 
        C.DESCRIPCION,
        C.LICENCIA,
        C.VIGENCIA AS VIGENCIA_LICENCIA,
        U.NOMBRE_USUARIO,
        U.NOMBRE,
        U.APELLIDO1 AS PATERNO,
        U.APELLIDO2 AS MATERNO,
        U.CORREO,
        VPC.NUMERO_DE_VIAJES,
        VPC.MONTO
    FROM VIAJES_POR_CONDUCTOR AS VPC
    JOIN USUARIOS.CONDUCTOR AS C ON C.ID_USUARIO = VPC.ID_USUARIO
    JOIN USUARIOS.USUARIO AS U ON U.ID_USUARIO = C.ID_USUARIO;
END;
GO
/*
 * 2. Consolidado mensual; día, monto total, monto mensual
*/



/*
 * 3. Top 5 de conductores por un periodo de tiempo
*/ 

CREATE PROCEDURE OBTENER_TOP_CONDUCTORES
	@FECHA_INICIO DATE,
	@FECHA_FIN DATE
AS
BEGIN
	
	SELECT TOP 5
		C.ID_USUARIO, 
		COUNT(*) AS 'CANTIDAD DE VIAJES'
	FROM USUARIOS.CONDUCTOR AS C
	JOIN USUARIOS.AUTOMOVIL AS A
	ON C.ID_USUARIO=A.ID_USUARIO
	JOIN OPERACIONES.VIAJE AS V
	ON V.ID_AUTOMOVIL=A.ID_AUTOMOVIL
	WHERE V.FECHA_INICIOVIAJE BETWEEN @FECHA_INICIO AND @FECHA_FIN
	GROUP BY C.ID_USUARIO
	ORDER BY COUNT(*) DESC
END;
GO
/*
 * 4. Top 5 de clientes, es decir, los clientes con mayor número de viajes (nombre completo y correo)
*/

CREATE PROCEDURE OBTENER_TOP_CLIENTES
	@FECHA_INICIO DATE,
	@FECHA_FIN DATE
AS
BEGIN
	
	WITH DATOS_CLIENTES AS (
		SELECT
			C.ID_USUARIO,
			COUNT(V.ID_VIAJE) AS NUMERO_DE_VIAJES
		FROM USUARIOS.CLIENTE AS C
		JOIN OPERACIONES.VIAJE AS V
		ON V.ID_USUARIO=C.ID_USUARIO
		WHERE V.FECHA_INICIOVIAJE BETWEEN @FECHA_INICIO AND @FECHA_FIN
		GROUP BY C.ID_USUARIO
	)

	SELECT TOP 5
		DC.ID_USUARIO, 
		DC.NUMERO_DE_VIAJES AS 'NUMERO DE VIAJES',
		U.NOMBRE + ' ' + U.APELLIDO1 + ' ' + ISNULL( ' '+U.APELLIDO2,'') AS 'NOMBRE COMPLETO',
		U.CORREO
	FROM DATOS_CLIENTES AS DC
	JOIN USUARIOS.USUARIO AS U
	ON U.ID_USUARIO=DC.ID_USUARIO
	ORDER BY DC.NUMERO_DE_VIAJES DESC;

END;
GO
/*
 * 5. Listado de conductores con más quejas y motivo (se maneja un catálogo, ejemplo, irrespetuoso, maneja
 * muy rápido, no respeta las reglas de vialidad, etc.)
*/
CREATE PROCEDURE CONDUCTORES_CON_MAS_QUEJAS
AS
BEGIN
	with datos_quejas as(
	SELECT top 3 count(*) as num_quejas, a.ID_AUTOMOVIL FROM OPERACIONES.VIAJE as v
	join INCIDENCIAS.QUEJA as q on v.ID_VIAJE=q.ID_VIAJE
	join USUARIOS.AUTOMOVIL as a on v.ID_AUTOMOVIL=a.ID_AUTOMOVIL
	group by a.ID_AUTOMOVIL)

	select dq.num_quejas, U.NOMBRE + ' ' + U.APELLIDO1 +ISNULL( ' '+U.APELLIDO2,'') AS 'NOMBRE COMPLETO', u.ID_USUARIO,
	cq.MOTIVO as motivo
	from datos_quejas as dq
	join OPERACIONES.VIAJE as v on dq.ID_AUTOMOVIL=v.ID_AUTOMOVIL
	join INCIDENCIAS.QUEJA as q on v.ID_VIAJE=q.ID_VIAJE
	join USUARIOS.AUTOMOVIL as a on v.ID_AUTOMOVIL=a.ID_AUTOMOVIL
	join CATALOGOS.CATALOGO_QUEJAS
	as cq on cq.ID_CATALOGO_QUEJAS=q.ID_CATALOGO_QUEJAS
	join USUARIOS.USUARIO as u on a.ID_USUARIO=u.ID_USUARIO
	order by num_quejas, ID_USUARIO
END;
GO


/*
 * 6. Listado de accidentes; fecha, ubicación, tipo, descripción, heridos si o no, monto gastado, nombre del
 * conductor y auto, si el conductor fue el responsable o no. Con filtros para poder obtener el listado desde un
 * día o un periodo de tiempo.
*/
CREATE PROCEDURE OBTENER_ACCIDENTES
	@FECHA_INICIO DATE,
	@FECHA_FIN DATE
AS
BEGIN
	
	SELECT AC.FECHA,AC.LATITUD,AC.LONGITUD, CA.TIPO,/*AC.DESCRIPCION,*/
	HERIDOS=CASE AC.HERIDOS
	WHEN 1 THEN 'EL CONDUCTOR ES RESPONSABLE'
	WHEN 0 THEN 'EL CONDUCTOR NO ES RESPONSABLE'
	END, AC.MONTO,
	U.NOMBRE + ' ' + U.APELLIDO1 +ISNULL( ' '+U.APELLIDO2,'') AS 'NOMBRE CONDUCTOR',
	A.NUMPLACAS,M.NOMBRE_MODELO,
	RESPONSABLE=CASE AC.ES_RESPONSABLE
	WHEN 1 THEN 'EL CONDUCTOR ES RESPONSABLE'
	WHEN 0 THEN 'EL CONDUCTOR NO ES RESPONSABLE'
	END
	FROM INCIDENCIAS.ACCIDENTE AS AC
	JOIN CATALOGOS.CATALOGO_ACCIDENTES AS CA ON  AC.ID_TIPO_ACCIDENTE=CA.ID_TIPO_ACCIDENTE
	JOIN OPERACIONES.VIAJE AS V ON AC.ID_VIAJE = V.ID_VIAJE
	JOIN USUARIOS.AUTOMOVIL AS A ON A.ID_AUTOMOVIL= V.ID_AUTOMOVIL
	JOIN USUARIOS.USUARIO AS U ON U.ID_USUARIO= A.ID_USUARIO
	JOIN CATALOGOS.MODELO AS M ON M.ID_MODELO= A.ID_MODELO
	WHERE V.FECHA_INICIOVIAJE BETWEEN @FECHA_INICIO AND @FECHA_FIN
	
END;
GO



/*
 * 7. Listado de los clientes con menos estrellas
*/
CREATE PROCEDURE CLIENTES_CON_MENOS_ESTRELLAS
AS
BEGIN
	with datos_clientes_menos_estrellas as(
	SELECT top 3 sum(CALIFICACION_CLIENTE) as CANTIDAD_ESTRELLAS, ID_USUARIO  from OPERACIONES.VIAJE
	GROUP BY ID_USUARIO
	ORDER BY SUM(CALIFICACION_CLIENTE) ASC
	)

	select u.ID_USUARIO, U.NOMBRE + ' ' + U.APELLIDO1 +ISNULL( ' '+U.APELLIDO2,'') AS 'NOMBRE COMPLETO', dcme.CANTIDAD_ESTRELLAS
	from USUARIOS.USUARIO as u
	join datos_clientes_menos_estrellas as dcme on  dcme.ID_USUARIO=u.ID_USUARIO
END;
GO


/*
 * 8. Listado de los conductores con el total que les han dado por cada estrella
*/
CREATE PROCEDURE ESTRELLAS_CONDUCTORES
AS
BEGIN
	with CANTIDAD_ESTRELLAS_CONDUCTORES as(
	SELECT ID_AUTOMOVIL, COUNT(*) as CANTIDAD_ESTRELLAS, CALIFICACION_CONDUCTOR   from OPERACIONES.VIAJE
	GROUP BY ID_AUTOMOVIL, CALIFICACION_CONDUCTOR
	)

	select u.ID_USUARIO, U.NOMBRE + ' ' + U.APELLIDO1 +ISNULL( ' '+U.APELLIDO2,'') AS 'NOMBRE COMPLETO', CEC.CALIFICACION_CONDUCTOR,cec.CANTIDAD_ESTRELLAS
	from USUARIOS.USUARIO as u
	JOIN USUARIOS.AUTOMOVIL AS a on u.ID_USUARIO=a.ID_USUARIO
	join CANTIDAD_ESTRELLAS_CONDUCTORES as CEC on  CEC.ID_AUTOMOVIL=a.ID_AUTOMOVIL
	order by [NOMBRE COMPLETO]--, CALIFICACION_CONDUCTOR
END;
select  * from USUARIOS.AUTOMOVIL
GO

/*
 * 9. Listado de autos, placa, número de serie, marca, modelo, año y color y su dueño
*/
select a.ID_AUTOMOVIL, a.NUMPLACAS,/*a.NUMSERIE,*/ ma.NOMBRE_MARCA,mo.NOMBRE_MODELO,a.AÑO,/*a.COLOR*/
U.NOMBRE + ' ' + U.APELLIDO1 +ISNULL( ' '+U.APELLIDO2,'') AS 'DUEÑO'
from USUARIOS.AUTOMOVIL as a
join USUARIOS.USUARIO as u on u.ID_USUARIO=a.ID_USUARIO
join CATALOGOS.MODELO as mo on mo.ID_MODELO=a.id_modelo 
join CATALOGOS.MARCA  as ma on ma.ID_MARCA=mo.ID_MARCA


/*
 * 10. Listado de quejas incluyendo el conductor y auto, con filtro para obtenerse por un periodo de tiempo o por
 * conductor
*/


